### ISSUE TITLE
Titles rings half shown OnePlus 6

### ISSUE THREAD

**Issue by anniekvandijk** [anniekvandijk/showringhelper-react-native#20]

**Comment by anniekvandijk** [comment]
Fixed for version 0.8.0

**Comment by anniekvandijk** [comment]
Fix 0.8.0 not working

**Comment by knilessew** [comment]
https://github.com/facebook/react-native/issues/25481

**Comment by anniekvandijk** [comment]
This solved issue on OnePlus6
`// utils.js
// One Plus Fix for Oxygen OS and its painful Slate font truncating on bold text
// https://github.com/facebook/react-native/issues/15114
export const opoFontFix = () => {
  if(Platform.OS !== 'android') {
    return
  }

  const oldRender = Text.render
  Text.render = function (...args) {
    const origin = oldRender.call(this, ...args);
    return React.cloneElement(origin, {
      style: [{fontFamily: 'Roboto'}, origin.props.style]
    })
  }
}
// App.js
import {opoFontFix} from './utils'

// One Plus Fix for Oxygen OS
opoFontFix()

//... rest of your code
export default class App extends Component<Props> {
}`
