### ISSUE TITLE
Android navigation flow when moving out of detailpage by clicking bottom navigation not correct

### ISSUE THREAD

**Issue by anniekvandijk** [anniekvandijk/showringhelper-react-native#22]
When leaving subpage via menu and going back. Subpage is visable.

On Android, mainpage must be shown.
On IOS, subpage must be shown.
https://material.io/design/components/bottom-navigation.html#behavior

**Comment by anniekvandijk** [comment]
Fix version 0.10.0

**Comment by knilessew** [comment]
Works
